version: 2
jobs:
  build:
    docker:
      - image: python:3

    steps:
      - checkout
      - run:
          name: Install python module.
          command: pip install -r requirements.txt
      - run:
          name: Run tests.
          command: python3 -m pytest --verbose --cov --cov-report=html:htmlcov ./tests/
      - store_test_results:
          path: htmlcov

      - store_artifacts:
          path: htmlcov

      - run:
          name: Upload to codecov.
          command: python3 -m codecov

